{{- if and .Values.basicAuth.enabled .Values.basicAuth.password (not .Values.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apprise.fullname" . }}-basic-auth
  labels:
    {{- include "apprise.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ htpasswd .Values.basicAuth.username .Values.basicAuth.password | b64enc }}
{{- end }}